Feature/1st schema definition
HottoCoffee/pre-HottoCoffee pull request #4
Opened 2023-03-03 08:50 UTC by seito2

# Summary
Add basic schema

## How to confirm
Please run swagger (refer to README.md) and confirm each endpoint is ok.

2023-03-04 02:12 UTC, T45K commented
CI落ちてるのは大丈夫な奴？

2023-03-04 02:41 UTC, T45K requested changes
Good first PR.
Thank you for setting up everything

2023-03-04 02:41 UTC, T45K commented on .github/workflows/firebase-hosting-merge.yml
> +      - uses: actions/checkout@v2
`checkout`はv3が出てたはず

2023-03-04 02:41 UTC, T45K commented on swagger/schema/schemas/batch.yaml
> +    time_limit:
これって分単位ですよね。ドキュメントのどっかにその辺の情報があると嬉しい

2023-03-04 02:41 UTC, T45K commented on swagger/schema/schemas/batch.yaml
> +    initial_date:
これもISO標準に準拠してるみたいな情報がどこかにあれば

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +  # 省略
?

2023-03-04 02:41 UTC, T45K commented on swagger/docs/404.html
> +<!DOCTYPE html>
この辺って自動生成されるファイルですか？
自動生成系はGit管理に含めずに、「ローカルで生成して手動デプロイか、Actionsでビルド&デプロイ」で良いかなぁと思いました
言葉足らずで申し訳ない

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +        "200":
キーワードに引っかからなければ200で空配列を返すでOKですよね？
descに空listを返しうるみたいな表現が欲しいかも

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +              $ref: "./schemas/batch.yaml#Batch"
400、500は省略？

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +          name: end_date
`end_date`はinclusiveなのかexclusiveなのか明記しといていただければ

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +          required: false
これ、`false`で大丈夫ですか？
`start_date`が空で`end_date`だけあるとき、`end_date`以前のデータを全部欲しいみたいな意図があったりします？

2023-03-04 02:41 UTC, T45K commented on swagger/schema/main.yaml
> +          description: batch not found.
`bad request`

2023-03-04 05:23 UTC, T45K commented on swagger/schema/schemas/batch.yaml
> +    - initial_date
実行間隔（cron形式で与えるやつ）が抜けてそう

2023-03-04 05:26 UTC, T45K commented on swagger/schema/schemas/batch.yaml
> +    status:
batchの情報がstatus持つの変だと思います。
historyに移すべき

2023-03-04 05:35 UTC, seito2 commented on swagger/docs/404.html
> +<!DOCTYPE html>
自動生成というか、Swaggerのbaseになるファイルです
Actionsでビルド&デプロイできなくはないんですが、今後一切変わることないので、コミットしておいてyamlだけ生成すれば良い状態にしたほうがCI早くなって良いかな〜と思ってこのようにしました！

2023-03-04 05:35 UTC, seito2 commented on swagger/schema/main.yaml
> +  # 省略
oh... Copy & paste issue. I'm sorry

2023-03-04 05:35 UTC, seito2 commented on swagger/schema/main.yaml
> +          required: false
> end_date以前のデータを全部欲しいみたいな
start_date, end_date両方の方向にこの状況あるかも？と思ったんですが初期実装ではなさそうなのでrequired: trueにします！ありがとうございますー

2023-03-04 07:44 UTC, T45K commented on swagger/schema/main.yaml
> +          required: false
end_dateがなかったら無限リストを返すことになる 🤔

2023-03-04 08:42 UTC, seito2 commented on swagger/schema/main.yaml
> +          required: false
ホントですね

2023-03-04 10:42 UTC, seito2 commented
@T45K 
Thank you for your comment, could you review again?

2023-03-04 11:06 UTC, T45K requested changes
looks good.
as i told in Viber, i'd like to review this in Mob-work style. see you later.

2023-03-04 11:06 UTC, T45K commented on swagger/schema/schemas/history.yaml
> +    enum: [before_started, in_progress, success, failed]
`enum` looks to be put in wrong position.
additional indent is needed?

2023-03-09 10:27 UTC, T45K requested changes

2023-03-09 10:27 UTC, T45K commented on swagger/schema/schemas/error.yaml
> +components:
why cannot we see these schema information (other than batch) on Swagger UI?

2023-03-09 10:27 UTC, T45K commented on swagger/schema/schemas/history.yaml
> +        history_id:
`history_id` can be null under only GET `/api/calendar` context.
could you add the supplement int this schema file?

2023-03-10 07:34 UTC, seito2 commented on swagger/schema/schemas/error.yaml
> +components:
it is because I didn't added schema reference into main.yaml.
I added.

2023-03-10 07:34 UTC, seito2 commented on swagger/schema/schemas/history.yaml
> +        history_id:
Thank you, I added

2023-03-10 07:36 UTC, seito2 commented
@T45K Thank you for your review!
I modify 1 thing without your review, separate batch schema for creating and for normal.
It is because client generation tool is not compatible for readOnly property.

2023-03-11 02:05 UTC, T45K approved these changes
Thank you for your great job.

2023-03-12 01:23 UTC, tikogr approved these changes
Sorry for the late review.

2023-03-12 03:02 UTC, merged